using Microsoft.EntityFrameworkCore;
using Hotdesk.EntityFramework.Models;

namespace Hotdesk.EntityFramework;

// Auto-generated by the Entity Framework toolchain from a temporary database defined by the schema.
public partial class HotdeskDbContext : DbContext
{
    public HotdeskDbContext(DbContextOptions<HotdeskDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Booking> bookings { get; set; }

    public virtual DbSet<Department> departments { get; set; }

    public virtual DbSet<Desk> desks { get; set; }

    public virtual DbSet<Floor> floors { get; set; }

    public virtual DbSet<Team> teams { get; set; }

    public virtual DbSet<User> users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.HasPostgresExtension("btree_gist");

        modelBuilder.Entity<Booking>(entity =>
        {
            entity.HasKey(e => e.booking_id).HasName("bookings_pkey");

            entity.Property(e => e.created_at)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp without time zone");
            entity.Property(e => e.end_time).HasColumnType("timestamp without time zone");
            entity.Property(e => e.start_time).HasColumnType("timestamp without time zone");
            entity.Property(e => e.status)
                .HasMaxLength(20)
                .HasDefaultValueSql("'confirmed'::character varying");

            entity.HasOne(d => d.desk).WithMany(p => p.bookings)
                .HasForeignKey(d => d.desk_id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("bookings_desk_id_fkey");

            entity.HasOne(d => d.user).WithMany(p => p.bookings)
                .HasForeignKey(d => d.user_id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("bookings_user_id_fkey");
        });

        modelBuilder.Entity<Department>(entity =>
        {
            entity.HasKey(e => e.department_id).HasName("departments_pkey");

            entity.Property(e => e.name).HasMaxLength(30);
        });

        modelBuilder.Entity<Desk>(entity =>
        {
            entity.HasKey(e => e.desk_id).HasName("desks_pkey");

            entity.Property(e => e.is_enabled).HasDefaultValue(true);
            entity.Property(e => e.label).HasMaxLength(50);
            entity.Property(e => e.x_coord).HasPrecision(5, 2);
            entity.Property(e => e.y_coord).HasPrecision(5, 2);

            entity.HasOne(d => d.floor).WithMany(p => p.desks)
                .HasForeignKey(d => d.floor_id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("desks_floor_id_fkey");
        });

        modelBuilder.Entity<Floor>(entity =>
        {
            entity.HasKey(e => e.floor_id).HasName("floors_pkey");

            entity.Property(e => e.name).HasMaxLength(50);
        });

        modelBuilder.Entity<Team>(entity =>
        {
            entity.HasKey(e => e.team_id).HasName("teams_pkey");

            entity.Property(e => e.name).HasMaxLength(100);

            entity.HasOne(d => d.department).WithMany(p => p.teams)
                .HasForeignKey(d => d.department_id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("teams_department_id_fkey");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.user_id).HasName("users_pkey");

            entity.HasIndex(e => e.email, "users_email_key").IsUnique();

            entity.Property(e => e.email).HasMaxLength(255);
            entity.Property(e => e.is_admin).HasDefaultValue(false);
            entity.Property(e => e.name).HasMaxLength(100);
            entity.Property(e => e.password_hash).HasMaxLength(255);

            entity.HasOne(d => d.team).WithMany(p => p.users)
                .HasForeignKey(d => d.team_id)
                .HasConstraintName("users_team_id_fkey");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
